/*
 * Copyright (C) 2022-2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef NFC_INFC_TAG_CALLBACK_H
#define NFC_INFC_TAG_CALLBACK_H

#include <iremote_stub.h>
#include "nfc_tag_errcode.h"

namespace OHOS {
namespace NFC {
// Value space of OnNotify(int) events:
// 0~2 consistent with HDI chip event ohos.hdi.connected_nfc_tag.v1_1.ConnectedNfcTagEvent (reported by driver)
// 3 and above are events generated by the service process iteself (not from the driver)
enum NfcTagNotifyEvent {
    NFC_TAG_EVENT_ENTER_FIELD   = 0, // From HDI: enter field
    NFC_TAG_EVENT_LEAVE_FIELD   = 1, // From HDI: leave field
    NFC_TAG_CHIP_RESTART        = 2, // From HDI: chip restart
    NFC_TAG_EVENT_INIT_COMPLETE = 3, // Genertated bt the service process: chip initialization complete
};

class INfcTagCallback : public IRemoteBroker {
public:
    virtual ErrCode OnNotify(int nfcRfState) = 0;
    enum {
        CMD_ON_NFC_TAG_NOTIFY = 0,
    };
public:
    DECLARE_INTERFACE_DESCRIPTOR(u"ohos.nfc.INfcTagCallback");
};
}  // namespace NFC
}  // namespace OHOS
#endif
